// <auto-generated />
using System;
using DigitalCursosAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DigitalCursosAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DigitalCursos.Models.Models.Aluno", b =>
                {
                    b.Property<int>("AlunoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Sobrenome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AlunoId");

                    b.HasIndex("CursoId");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            AlunoId = 1,
                            CursoId = 1,
                            Email = "felipe@email.com",
                            Genero = 0,
                            Nascimento = new DateTime(2002, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Felipe",
                            Sobrenome = "Ribeiro"
                        },
                        new
                        {
                            AlunoId = 2,
                            CursoId = 2,
                            Email = "maria@email.com",
                            Genero = 1,
                            Nascimento = new DateTime(2001, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Maria",
                            Sobrenome = "Silveira"
                        });
                });

            modelBuilder.Entity("DigitalCursos.Models.Models.Curso", b =>
                {
                    b.Property<int>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("int");

                    b.Property<string>("CursoNome")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("varbinary(max)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CursoId");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            CursoId = 1,
                            CargaHoraria = 40,
                            CursoNome = "CSharp Basico",
                            Descricao = "Curso de C# Básico",
                            Inicio = new DateTime(2021, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 150.00m
                        },
                        new
                        {
                            CursoId = 2,
                            CargaHoraria = 40,
                            CursoNome = "Asp .Net Core Basico",
                            Descricao = "Asp .Net Core Básico",
                            Inicio = new DateTime(2021, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Preco = 250.00m
                        });
                });

            modelBuilder.Entity("DigitalCursos.Models.Models.Aluno", b =>
                {
                    b.HasOne("DigitalCursos.Models.Models.Curso", "Curso")
                        .WithMany("Alunos")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("DigitalCursos.Models.Models.Curso", b =>
                {
                    b.Navigation("Alunos");
                });
#pragma warning restore 612, 618
        }
    }
}
